version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_database
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DATABASE: ${PG_DATABASE}

  # cache:
  #   image: redis:latest
  #   container_name: ${COMPOSE_PROJECT_NAME}-cache
  #   restart: always
  #   expose:
  #     - ${REDIS_PORT}
  #   volumes:
  #     - cache:/data
  #   command: redis-server --save 20 1 --loglevel warning

  api:
    container_name: ${COMPOSE_PROJECT_NAME}_api
    restart: always
    build: DockerFile
    ports:
      - 8000:8000
    # environment:
    #   REDIS_HOST: cache
    # links:
    #   - ${COMPOSE_PROJECT_NAME}-cache
    depends_on:
      - postgres
      # - cache
# volumes:
#   cache:
#     driver: local
