version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_database
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  # cache:
  #   image: redis:latest
  #   container_name: ${COMPOSE_PROJECT_NAME}-cache
  #   restart: always
  #   expose:
  #     - ${REDIS_PORT}
  #   volumes:
  #     - cache:/data
  #   command: redis-server --save 20 1 --loglevel warning

  api:
    image: node:latest
    container_name: ${COMPOSE_PROJECT_NAME}_api
    restart: always
    ports:
      - 8000:8000
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    environment:
      PG_HOST: postgres
    #   REDIS_HOST: cache
    # links:
    #   - ${COMPOSE_PROJECT_NAME}-cache
    depends_on:
      - postgres
      # - cache
    command: bash -c "rm -rf node_modules build && npm i && npm run build && npm start"
# volumes:
#   cache:
#     driver: local
